name: amp-rbc-md
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - gromacs=2024
  - biopython
  - click
  - pyyaml
  - pandas=1.5.3
  - numpy=1.24.3
  - tqdm
  - matplotlib
  - mlflow
  - moviepy
  - rich
  - pytest
  - pytest-cov
  - black
  - flake8
  - mypy
  - isort 
  - pip
  - pip:
      # GPU-abh채ngige Python-Pakete
      - colabfold>=1.5.5  # AlphaFold2-Implementierung f체r Strukturvorhersage
      - omegaconf
      # Kompatible JAX-Versionen f체r ColabFold mit CUDA-Unterst체tzung
      - "jax>=0.6.0"
      - "jaxlib>=0.6.0"
      - "chex==0.1.7" 